#!/usr/bin/env python3
"""
Full translation script for ai-soulgen.com
Extracts all text nodes from EN index.html, translates them, and applies to all lang subfolders.
"""

import os
import re
import json

# Language codes and their properties
LANGS = {
    'fr': {'name': 'French', 'locale': 'fr_FR', 'currency': 'EUR'},
    'de': {'name': 'German', 'locale': 'de_DE', 'currency': 'EUR'},
    'es': {'name': 'Spanish', 'locale': 'es_ES', 'currency': 'EUR'},
    'it': {'name': 'Italian', 'locale': 'it_IT', 'currency': 'EUR'},
    'pt': {'name': 'Portuguese', 'locale': 'pt_PT', 'currency': 'EUR'},
    'nl': {'name': 'Dutch', 'locale': 'nl_NL', 'currency': 'EUR'},
    'pl': {'name': 'Polish', 'locale': 'pl_PL', 'currency': 'PLN'},
    'ru': {'name': 'Russian', 'locale': 'ru_RU', 'currency': 'RUB'},
    'tr': {'name': 'Turkish', 'locale': 'tr_TR', 'currency': 'TRY'},
    'ja': {'name': 'Japanese', 'locale': 'ja_JP', 'currency': 'JPY'},
    'kr': {'name': 'Korean', 'locale': 'ko_KR', 'currency': 'KRW'},
    'hi': {'name': 'Hindi', 'locale': 'hi_IN', 'currency': 'INR'},
}

# Translation dictionaries (complete)
TRANSLATIONS = {
    'fr': {
        'AI SoulGen': 'AI SoulGen',
        'The ultimate AI soulmate and character generator': 'Le générateur de personnages et âme sœur IA ultime',
        'Create your dream companion in seconds. Realistic portraits, anime characters, and AI video — all from a simple text prompt.': 'Créez votre compagnon de rêve en quelques secondes. Portraits réalistes, personnages anime et vidéo IA — le tout à partir d\'un simple texte.',
        'Start Creating Free': 'Commencer Gratuitement',
        'Real Character': 'Personnage Réel',
        'Anime Character': 'Personnage Anime',
        'DreamTwin Couple': 'Couple DreamTwin',
        'AI SoulGen transforms text prompts into realistic or anime characters': 'AI SoulGen transforme les textes en personnages réalistes ou anime',
        'Describe any character and AI SoulGen brings it to life in seconds': 'Décrivez n\'importe quel personnage et AI SoulGen le fait vivre en secondes',
        'Create Your Dream': 'Créez Votre Rêve',
        'Sign Up Free': 'Inscription Gratuite',
        'How It Works': 'Comment Ça Marche',
        'Choose Your Style': 'Choisissez Votre Style',
        'Real Character for photorealistic, Anime Character for stylized art, or DreamTwin for romantic pairs': 'Personnage Réel pour du photoréaliste, Anime pour l\'art stylisé, ou DreamTwin pour des couples romantiques',
        'Describe Your Vision': 'Décrivez Votre Vision',
        'Generate & Customize': 'Générez & Personnalisez',
        'Features': 'Fonctionnalités',
        'Text-to-Image Generation': 'Génération Texte-en-Image',
        'Look-Alike Portrait Creator': 'Créateur de Portraits Ressemblants',
        'AI Video Generator': 'Générateur de Vidéo IA',
        'SoulChat Companion': 'Compagnon SoulChat',
        'Face Swap & Sequence': 'Face Swap & Séquence',
        'AI Outpainting & Editing': 'AI Outpainting & Édition',
        'Pricing': 'Tarifs',
        'Free': 'Gratuit',
        'Pro Monthly': 'Pro Mensuel',
        'Pro Yearly': 'Pro Annuel',
        'FAQ': 'FAQ',
        'Blog': 'Blog',
        'Contact': 'Contact',
        'Privacy Policy': 'Politique de Confidentialité',
        'Terms of Service': 'Conditions d\'Utilisation',
        'Affiliate Disclosure': 'Divulgation d\'Affiliation',
        'Compare': 'Comparer',
        'vs Candy AI': 'vs Candy AI',
        'vs Seduced AI': 'vs Seduced AI',
        'vs DreamGF': 'vs DreamGF',
        'What is AI SoulGen?': 'Qu\'est-ce qu\'AI SoulGen ?',
        'Is AI SoulGen free?': 'AI SoulGen est-il gratuit ?',
        'How does the credit system work?': 'Comment fonctionne le système de crédits ?',
        'Can I generate video?': 'Puis-je générer des vidéos ?',
        'Is AI SoulGen legit?': 'AI SoulGen est-il légitime ?',
        'Does it work on mobile?': 'Ça marche sur mobile ?',
        'Ready to Create Your Dream Character?': 'Prêt à Créer Votre Personnage de Rêve ?',
        'Join thousands of creators already generating stunning AI characters. Your first image is just seconds away.': 'Rejoignez des milliers de créateurs qui génèrent déjà des personnages IA époustouflants. Votre première image est à quelques secondes.',
        '© 2026 AI SoulGen. All rights reserved.': '© 2026 AI SoulGen. Tous droits réservés.',
    },
    'de': {
        'AI SoulGen': 'AI SoulGen',
        'The ultimate AI soulmate and character generator': 'Der ultimative KI-Seelenverwandte und Charaktergenerator',
        'Create your dream companion in seconds. Realistic portraits, anime characters, and AI video — all from a simple text prompt.': 'Erstelle deinen Traumbegleiter in Sekunden. Realistische Porträts, Anime-Charaktere und KI-Video — alles aus einem einfachen Text.',
        'Start Creating Free': 'Kostenlos Erstellen',
        'Real Character': 'Echter Charakter',
        'Anime Character': 'Anime-Charakter',
        'DreamTwin Couple': 'DreamTwin Paar',
        'AI SoulGen transforms text prompts into realistic or anime characters': 'AI SoulGen verwandelt Texte in realistische oder Anime-Charaktere',
        'Describe any character and AI SoulGen brings it to life in seconds': 'Beschreibe einen Charakter und AI SoulGen bringt ihn in Sekunden zum Leben',
        'Create Your Dream': 'Erstelle Deinen Traum',
        'Sign Up Free': 'Kostenlos Anmelden',
        'How It Works': 'Wie Es Funktioniert',
        'Choose Your Style': 'Wähle Deinen Stil',
        'Real Character for photorealistic, Anime Character for stylized art, or DreamTwin for romantic pairs': 'Echter Charakter für Fotorealismus, Anime für stilisierte Kunst oder DreamTwin für romantische Paare',
        'Describe Your Vision': 'Beschreibe Deine Vision',
        'Generate & Customize': 'Generieren & Anpassen',
        'Features': 'Funktionen',
        'Text-to-Image Generation': 'Text-zu-Bild-Generierung',
        'Look-Alike Portrait Creator': 'Look-Alike-Portrait-Ersteller',
        'AI Video Generator': 'KI-Video-Generator',
        'SoulChat Companion': 'SoulChat-Begleiter',
        'Face Swap & Sequence': 'Face Swap & Sequenz',
        'AI Outpainting & Editing': 'KI-Outpainting & Bearbeitung',
        'Pricing': 'Preise',
        'Free': 'Kostenlos',
        'Pro Monthly': 'Pro Monatlich',
        'Pro Yearly': 'Pro Jährlich',
        'FAQ': 'FAQ',
        'Blog': 'Blog',
        'Contact': 'Kontakt',
        'Privacy Policy': 'Datenschutzrichtlinie',
        'Terms of Service': 'Nutzungsbedingungen',
        'Affiliate Disclosure': 'Affiliate-Offenlegung',
        'Compare': 'Vergleichen',
        'vs Candy AI': 'vs Candy AI',
        'vs Seduced AI': 'vs Seduced AI',
        'vs DreamGF': 'vs DreamGF',
        'What is AI SoulGen?': 'Was ist AI SoulGen?',
        'Is AI SoulGen free?': 'Ist AI SoulGen kostenlos?',
        'How does the credit system work?': 'Wie funktioniert das Credit-System?',
        'Can I generate video?': 'Kann ich Videos generieren?',
        'Is AI SoulGen legit?': 'Ist AI SoulGen legitim?',
        'Does it work on mobile?': 'Funktioniert es auf dem Handy?',
        'Ready to Create Your Dream Character?': 'Bereit, deinen Traumcharakter zu erstellen?',
        'Join thousands of creators already generating stunning AI characters. Your first image is just seconds away.': 'Schließe dich Tausenden von Erstellern an, die bereits atemberaubende KI-Charaktere generieren. Dein erstes Bild ist nur Sekunden entfernt.',
        '© 2026 AI SoulGen. All rights reserved.': '© 2026 AI SoulGen. Alle Rechte vorbehalten.',
    },
    'es': {
        'AI SoulGen': 'AI SoulGen',
        'The ultimate AI soulmate and character generator': 'El generador de personajes y alma gemela definitivo',
        'Create your dream companion in seconds. Realistic portraits, anime characters, and AI video — all from a simple text prompt.': 'Crea tu compañero de ensueño en segundos. Retratos realistas, personajes anime y video IA — todo desde un simple texto.',
        'Start Creating Free': 'Empezar Gratis',
        'Real Character': 'Personaje Real',
        'Anime Character': 'Personaje Anime',
        'DreamTwin Couple': 'Pareja DreamTwin',
        'AI SoulGen transforms text prompts into realistic or anime characters': 'AI SoulGen transforma textos en personajes realistas o anime',
        'Describe any character and AI SoulGen brings it to life in seconds': 'Describe cualquier personaje y AI SoulGen lo hace realidad en segundos',
        'Create Your Dream': 'Crea Tu Sueño',
        'Sign Up Free': 'Regístrate Gratis',
        'How It Works': 'Cómo Funciona',
        'Choose Your Style': 'Elige Tu Estilo',
        'Real Character for photorealistic, Anime Character for stylized art, or DreamTwin for romantic pairs': 'Personaje Real para fotorrealismo, Anime para arte estilizado o DreamTwin para parejas románticas',
        'Describe Your Vision': 'Describe Tu Visión',
        'Generate & Customize': 'Genera y Personaliza',
        'Features': 'Características',
        'Text-to-Image Generation': 'Generación Texto-a-Imagen',
        'Look-Alike Portrait Creator': 'Creador de Retratos Parecidos',
        'AI Video Generator': 'Generador de Video IA',
        'SoulChat Companion': 'Compañero SoulChat',
        'Face Swap & Sequence': 'Face Swap y Secuencia',
        'AI Outpainting & Editing': 'AI Outpainting y Edición',
        'Pricing': 'Precios',
        'Free': 'Gratis',
        'Pro Monthly': 'Pro Mensual',
        'Pro Yearly': 'Pro Anual',
        'FAQ': 'Preguntas Frecuentes',
        'Blog': 'Blog',
        'Contact': 'Contacto',
        'Privacy Policy': 'Política de Privacidad',
        'Terms of Service': 'Términos de Servicio',
        'Affiliate Disclosure': 'Divulgación de Afiliados',
        'Compare': 'Comparar',
        'vs Candy AI': 'vs Candy AI',
        'vs Seduced AI': 'vs Seduced AI',
        'vs DreamGF': 'vs DreamGF',
        'What is AI SoulGen?': '¿Qué es AI SoulGen?',
        'Is AI SoulGen free?': '¿Es gratis AI SoulGen?',
        'How does the credit system work?': '¿Cómo funciona el sistema de créditos?',
        'Can I generate video?': '¿Puedo generar video?',
        'Is AI SoulGen legit?': '¿Es legítimo AI SoulGen?',
        'Does it work on mobile?': '¿Funciona en móvil?',
        'Ready to Create Your Dream Character?': '¿Listo para crear tu personaje de ensueño?',
        'Join thousands of creators already generating stunning AI characters. Your first image is just seconds away.': 'Únete a miles de creadores que ya generan personajes IA increíbles. Tu primera imagen está a segundos.',
        '© 2026 AI SoulGen. All rights reserved.': '© 2026 AI SoulGen. Todos los derechos reservados.',
    },
    'it': {
        'AI SoulGen': 'AI SoulGen',
        'The ultimate AI soulmate and character generator': 'Il generatore di personaggi e anima gemella definitivo',
        'Create your dream companion in seconds. Realistic portraits, anime characters, and AI video — all from a simple text prompt.': 'Crea il tuo compagno dei sogni in pochi secondi. Ritratti realistici, personaggi anime e video IA — tutto da un semplice testo.',
        'Start Creating Free': 'Inizia Gratis',
        'Real Character': 'Personaggio Reale',
        'Anime Character': 'Personaggio Anime',
        'DreamTwin Couple': 'Coppia DreamTwin',
        'AI SoulGen transforms text prompts into realistic or anime characters': 'AI SoulGen trasforma i testi in personaggi realistici o anime',
        'Describe any character and AI SoulGen brings it to life in seconds': 'Descrivi qualsiasi personaggio e AI SoulGen lo fa vivere in secondi',
        'Create Your Dream': 'Crea Il Tuo Sogno',
        'Sign Up Free': 'Iscriviti Gratis',
        'How It Works': 'Come Funziona',
        'Choose Your Style': 'Scegli Il Tuo Stile',
        'Real Character for photorealistic, Anime Character for stylized art, or DreamTwin for romantic pairs': 'Personaggio Reale per fotorealismo, Anime per arte stilizzata o DreamTwin per coppie romantiche',
        'Describe Your Vision': 'Descrivi La Tua Visione',
        'Generate & Customize': 'Genera e Personalizza',
        'Features': 'Funzionalità',
        'Text-to-Image Generation': 'Generazione Testo-Immagine',
        'Look-Alike Portrait Creator': 'Creatore di Ritratti Somiglianti',
        'AI Video Generator': 'Generatore Video IA',
        'SoulChat Companion': 'Compagno SoulChat',
        'Face Swap & Sequence': 'Face Swap e Sequenza',
        'AI Outpainting & Editing': 'AI Outpainting e Modifica',
        'Pricing': 'Prezzi',
        'Free': 'Gratis',
        'Pro Monthly': 'Pro Mensile',
        'Pro Yearly': 'Pro Annuale',
        'FAQ': 'Domande Frequenti',
        'Blog': 'Blog',
        'Contact': 'Contatto',
        'Privacy Policy': 'Informativa sulla Privacy',
        'Terms of Service': 'Termini di Servizio',
        'Affiliate Disclosure': 'Divulgazione Affiliati',
        'Compare': 'Confronta',
        'vs Candy AI': 'vs Candy AI',
        'vs Seduced AI': 'vs Seduced AI',
        'vs DreamGF': 'vs DreamGF',
        'What is AI SoulGen?': 'Cos\'è AI SoulGen?',
        'Is AI SoulGen free?': 'AI SoulGen è gratis?',
        'How does the credit system work?': 'Come funziona il sistema di crediti?',
        'Can I generate video?': 'Posso generare video?',
        'Is AI SoulGen legit?': 'AI SoulGen è legittimo?',
        'Does it work on mobile?': 'Funziona su mobile?',
        'Ready to Create Your Dream Character?': 'Pronto a creare il tuo personaggio dei sogni?',
        'Join thousands of creators already generating stunning AI characters. Your first image is just seconds away.': 'Unisciti a migliaia di creatori che generano già personaggi IA straordinari. La tua prima immagine è a pochi secondi.',
        '© 2026 AI SoulGen. All rights reserved.': '© 2026 AI SoulGen. Tutti i diritti riservati.',
    },
    'pt': {
        'AI SoulGen': 'AI SoulGen',
        'The ultimate AI soulmate and character generator': 'O gerador de personagens e alma gêmea definitivo',
        'Create your dream companion in seconds. Realistic portraits, anime characters, and AI video — all from a simple text prompt.': 'Crie seu companheiro dos sonhos em segundos. Retratos realistas, personagens anime e vídeo IA — tudo a partir de um simples texto.',
        'Start Creating Free': 'Começar Grátis',
        'Real Character': 'Personagem Real',
        'Anime Character': 'Personagem Anime',
        'DreamTwin Couple': 'Casal DreamTwin',
        'AI SoulGen transforms text prompts into realistic or anime characters': 'AI SoulGen transforma textos em personagens realistas ou anime',
        'Describe any character and AI SoulGen brings it to life in seconds': 'Descreva qualquer personagem e AI SoulGen o traz à vida em segundos',
        'Create Your Dream': 'Crie Seu Sonho',
        'Sign Up Free': 'Cadastre-se Grátis',
        'How It Works': 'Como Funciona',
        'Choose Your Style': 'Escolha Seu Estilo',
        'Real Character for photorealistic, Anime Character for stylized art, or DreamTwin for romantic pairs': 'Personagem Real para fotorrealismo, Anime para arte estilizada ou DreamTwin para casais românticos',
        'Describe Your Vision': 'Descreva Sua Visão',
        'Generate & Customize': 'Gere e Personalize',
        'Features': 'Recursos',
        'Text-to-Image Generation': 'Geração Texto-Imagem',
        'Look-Alike Portrait Creator': 'Criador de Retratos Parecidos',
        'AI Video Generator': 'Gerador de Vídeo IA',
        'SoulChat Companion': 'Companheiro SoulChat',
        'Face Swap & Sequence': 'Face Swap e Sequência',
        'AI Outpainting & Editing': 'AI Outpainting e Edição',
        'Pricing': 'Preços',
        'Free': 'Grátis',
        'Pro Monthly': 'Pro Mensal',
        'Pro Yearly': 'Pro Anual',
        'FAQ': 'Perguntas Frequentes',
        'Blog': 'Blog',
        'Contact': 'Contato',
        'Privacy Policy': 'Política de Privacidade',
        'Terms of Service': 'Termos de Serviço',
        'Affiliate Disclosure': 'Divulgação de Afiliados',
        'Compare': 'Comparar',
        'vs Candy AI': 'vs Candy AI',
        'vs Seduced AI': 'vs Seduced AI',
        'vs DreamGF': 'vs DreamGF',
        'What is AI SoulGen?': 'O que é AI SoulGen?',
        'Is AI SoulGen free?': 'AI SoulGen é grátis?',
        'How does the credit system work?': 'Como funciona o sistema de créditos?',
        'Can I generate video?': 'Posso gerar vídeo?',
        'Is AI SoulGen legit?': 'AI SoulGen é legítimo?',
        'Does it work on mobile?': 'Funciona no celular?',
        'Ready to Create Your Dream Character?': 'Pronto para criar seu personagem dos sonhos?',
        'Join thousands of creators already generating stunning AI characters. Your first image is just seconds away.': 'Junte-se a milhares de criadores que já geram personagens IA incríveis. Sua primeira imagem está a segundos.',
        '© 2026 AI SoulGen. All rights reserved.': '© 2026 AI SoulGen. Todos os direitos reservados.',
    },
    'nl': {
        'AI SoulGen': 'AI SoulGen',
        'The ultimate AI soulmate and character generator': 'De ultieme AI-zielsverwant en karaktergenerator',
        'Create your dream companion in seconds. Realistic portraits, anime characters, and AI video — all from a simple text prompt.': 'Creëer je droomgezel in seconden. Realistische portretten, anime-karakters en AI-video — allemaal van een simpele tekst.',
        'Start Creating Free': 'Gratis Beginnen',
        'Real Character': 'Echt Karakter',
        'Anime Character': 'Anime Karakter',
        'DreamTwin Couple': 'DreamTwin Koppel',
        'AI SoulGen transforms text prompts into realistic or anime characters': 'AI SoulGen transformeert teksten in realistische of anime-karakters',
        'Describe any character and AI SoulGen brings it to life in seconds': 'Beschrijf een karakter en AI SoulGen brengt het in seconden tot leven',
        'Create Your Dream': 'Creëer Je Droom',
        'Sign Up Free': 'Gratis Aanmelden',
        'How It Works': 'Hoe Het Werkt',
        'Choose Your Style': 'Kies Je Stijl',
        'Real Character for photorealistic, Anime Character for stylized art, or DreamTwin for romantic pairs': 'Echt Karakter voor fotorealisme, Anime voor gestileerde kunst of DreamTwin voor romantische koppels',
        'Describe Your Vision': 'Beschrijf Je Visie',
        'Generate & Customize': 'Genereer & Pas Aan',
        'Features': 'Functies',
        'Text-to-Image Generation': 'Tekst-naar-Afbeelding Generatie',
        'Look-Alike Portrait Creator': 'Look-Alike Portret Maker',
        'AI Video Generator': 'AI Video Generator',
        'SoulChat Companion': 'SoulChat Metgezel',
        'Face Swap & Sequence': 'Face Swap & Sequentie',
        'AI Outpainting & Editing': 'AI Outpainting & Bewerking',
        'Pricing': 'Prijzen',
        'Free': 'Gratis',
        'Pro Monthly': 'Pro Maandelijks',
        'Pro Yearly': 'Pro Jaarlijks',
        'FAQ': 'Veelgestelde Vragen',
        'Blog': 'Blog',
        'Contact': 'Contact',
        'Privacy Policy': 'Privacybeleid',
        'Terms of Service': 'Gebruiksvoorwaarden',
        'Affiliate Disclosure': 'Affiliate Openlegging',
        'Compare': 'Vergelijken',
        'vs Candy AI': 'vs Candy AI',
        'vs Seduced AI': 'vs Seduced AI',
        'vs DreamGF': 'vs DreamGF',
        'What is AI SoulGen?': 'Wat is AI SoulGen?',
        'Is AI SoulGen free?': 'Is AI SoulGen gratis?',
        'How does the credit system work?': 'Hoe werkt het creditsysteem?',
        'Can I generate video?': 'Kan ik video genereren?',
        'Is AI SoulGen legit?': 'Is AI SoulGen legitiem?',
        'Does it work on mobile?': 'Werkt het op mobiel?',
        'Ready to Create Your Dream Character?': 'Klaar om je droomkarakter te creëren?',
        'Join thousands of creators already generating stunning AI characters. Your first image is just seconds away.': 'Sluit je aan bij duizenden makers die al verbluffende AI-karakters genereren. Je eerste afbeelding is slechts seconden verwijderd.',
        '© 2026 AI SoulGen. All rights reserved.': '© 2026 AI SoulGen. Alle rechten voorbehouden.',
    },
    'pl': {
        'AI SoulGen': 'AI SoulGen',
        'The ultimate AI soulmate and character generator': 'Ostateczny generator postaci i bratniej duszy AI',
        'Create your dream companion in seconds. Realistic portraits, anime characters, and AI video — all from a simple text prompt.': 'Stwórz wymarzonego towarzysza w kilka sekund. Realistyczne portrety, postacie anime i wideo AI — wszystko z prostego tekstu.',
        'Start Creating Free': 'Zacznij Za Darmo',
        'Real Character': 'Prawdziwa Postać',
        'Anime Character': 'Postać Anime',
        'DreamTwin Couple': 'Para DreamTwin',
        'AI SoulGen transforms text prompts into realistic or anime characters': 'AI SoulGen zamienia teksty na realistyczne lub anime postacie',
        'Describe any character and AI SoulGen brings it to life in seconds': 'Opisz dowolną postać, a AI SoulGen ożywi ją w kilka sekund',
        'Create Your Dream': 'Stwórz Swoje Marzenie',
        'Sign Up Free': 'Zarejestruj Się Za Darmo',
        'How It Works': 'Jak To Działa',
        'Choose Your Style': 'Wybierz Sój Styl',
        'Real Character for photorealistic, Anime Character for stylized art, or DreamTwin for romantic pairs': 'Prawdziwa Postać dla fotorealizmu, Anime dla stylizowanej sztuki lub DreamTwin dla romantycznych par',
        'Describe Your Vision': 'Opisz Swoją Wizję',
        'Generate & Customize': 'Generuj i Dostosuj',
        'Features': 'Funkcje',
        'Text-to-Image Generation': 'Generowanie Tekst-na-Obraz',
        'Look-Alike Portrait Creator': 'Twórca Portretów Podobnych',
        'AI Video Generator': 'Generator Wideo AI',
        'SoulChat Companion': 'Towarzysz SoulChat',
        'Face Swap & Sequence': 'Face Swap i Sekwencja',
        'AI Outpainting & Editing': 'AI Outpainting i Edycja',
        'Pricing': 'Cennik',
        'Free': 'Darmowy',
        'Pro Monthly': 'Pro Miesięczny',
        'Pro Yearly': 'Pro Roczny',
        'FAQ': 'FAQ',
        'Blog': 'Blog',
        'Contact': 'Kontakt',
        'Privacy Policy': 'Polityka Prywatności',
        'Terms of Service': 'Warunki Korzystania',
        'Affiliate Disclosure': 'Ujawnienie Afiliacyjne',
        'Compare': 'Porównaj',
        'vs Candy AI': 'vs Candy AI',
        'vs Seduced AI': 'vs Seduced AI',
        'vs DreamGF': 'vs DreamGF',
        'What is AI SoulGen?': 'Co to jest AI SoulGen?',
        'Is AI SoulGen free?': 'Czy AI SoulGen jest darmowy?',
        'How does the credit system work?': 'Jak działa system kredytów?',
        'Can I generate video?': 'Czy mogę generować wideo?',
        'Is AI SoulGen legit?': 'Czy AI SoulGen jest legalny?',
        'Does it work on mobile?': 'Czy działa na telefonie?',
        'Ready to Create Your Dream Character?': 'Gotowy stworzyć wymarzoną postać?',
        'Join thousands of creators already generating stunning AI characters. Your first image is just seconds away.': 'Dołącz do tysięcy twórców, którzy już generują oszałamiające postacie AI. Twój pierwszy obraz jest o kilka sekund.',
        '© 2026 AI SoulGen. All rights reserved.': '© 2026 AI SoulGen. Wszelkie prawa zastrzeżone.',
    },
    'ru': {
        'AI SoulGen': 'AI SoulGen',
        'The ultimate AI soulmate and character generator': 'Лучший генератор персонажей и родственной души с ИИ',
        'Create your dream companion in seconds. Realistic portraits, anime characters, and AI video — all from a simple text prompt.': 'Создайте своего идеального спутника за секунды. Реалистичные портреты, персонажи аниме и видео с ИИ — всё из простого текста.',
        'Start Creating Free': 'Начать Бесплатно',
        'Real Character': 'Реальный Персонаж',
        'Anime Character': 'Персонаж Аниме',
        'DreamTwin Couple': 'Пара DreamTwin',
        'AI SoulGen transforms text prompts into realistic or anime characters': 'AI SoulGen превращает текст в реалистичных или аниме-персонажей',
        'Describe any character and AI SoulGen brings it to life in seconds': 'Опишите любого персонажа, и AI SoulGen оживит его за секунды',
        'Create Your Dream': 'Создай Свою Мечту',
        'Sign Up Free': 'Зарегистрироваться Бесплатно',
        'How It Works': 'Как Это Работает',
        'Choose Your Style': 'Выбери Свой Стиль',
        'Real Character for photorealistic, Anime Character for stylized art, or DreamTwin for romantic pairs': 'Реальный Персонаж для фотореализма, Аниме для стилизованного искусства или DreamTwin для романтических пар',
        'Describe Your Vision': 'Опиши Свое Видение',
        'Generate & Customize': 'Генерируй и Настраивай',
        'Features': 'Функции',
        'Text-to-Image Generation': 'Генерация Текст-в-Изображение',
        'Look-Alike Portrait Creator': 'Создатель Портретов-Похожих',
        'AI Video Generator': 'ИИ Генератор Видео',
        'SoulChat Companion': 'Компаньон SoulChat',
        'Face Swap & Sequence': 'Face Swap и Последовательность',
        'AI Outpainting & Editing': 'ИИ Аутпейнтинг и Редактирование',
        'Pricing': 'Цены',
        'Free': 'Бесплатно',
        'Pro Monthly': 'Pro Ежемесячный',
        'Pro Yearly': 'Pro Ежегодный',
        'FAQ': 'Частые Вопросы',
        'Blog': 'Блог',
        'Contact': 'Контакты',
        'Privacy Policy': 'Политика Конфиденциальности',
        'Terms of Service': 'Условия Использования',
        'Affiliate Disclosure': 'Раскрытие Информации о Партнёрстве',
        'Compare': 'Сравнить',
        'vs Candy AI': 'vs Candy AI',
        'vs Seduced AI': 'vs Seduced AI',
        'vs DreamGF': 'vs DreamGF',
        'What is AI SoulGen?': 'Что такое AI SoulGen?',
        'Is AI SoulGen free?': 'AI SoulGen бесплатен?',
        'How does the credit system work?': 'Как работает система кредитов?',
        'Can I generate video?': 'Можно ли генерировать видео?',
        'Is AI SoulGen legit?': 'AI SoulGen легален?',
        'Does it work on mobile?': 'Работает ли на телефоне?',
        'Ready to Create Your Dream Character?': 'Готовы создать персонажа своей мечты?',
        'Join thousands of creators already generating stunning AI characters. Your first image is just seconds away.': 'Присоединяйтесь к тысячам создателей, уже генерирующих потрясающих персонажей с ИИ. Ваше первое изображение — всего через несколько секунд.',
        '© 2026 AI SoulGen. All rights reserved.': '© 2026 AI SoulGen. Все права защищены.',
    },
    'tr': {
        'AI SoulGen': 'AI SoulGen',
        'The ultimate AI soulmate and character generator': 'Nihai AI ruh eşi ve karakter oluşturucu',
        'Create your dream companion in seconds. Realistic portraits, anime characters, and AI video — all from a simple text prompt.': 'Hayalinizdeki arkadaşı saniyeler içinde oluşturun. Gerçekçi portreler, anime karakterleri ve AI video — hepsi basit bir metinden.',
        'Start Creating Free': 'Ücretsiz Başla',
        'Real Character': 'Gerçek Karakter',
        'Anime Character': 'Anime Karakteri',
        'DreamTwin Couple': 'DreamTwin Çifti',
        'AI SoulGen transforms text prompts into realistic or anime characters': 'AI SoulGen metinleri gerçekçi veya anime karakterlere dönüştürür',
        'Describe any character and AI SoulGen brings it to life in seconds': 'Herhangi bir karakteri tanımlayın, AI SoulGen onu saniyeler içinde canlandırsın',
        'Create Your Dream': 'Hayalini Yarat',
        'Sign Up Free': 'Ücretsiz Kaydol',
        'How It Works': 'Nasıl Çalışır',
        'Choose Your Style': 'Stilini Seç',
        'Real Character for photorealistic, Anime Character for stylized art, or DreamTwin for romantic pairs': 'Fotorealizm için Gerçek Karakter, stilize sanat için Anime veya romantik çiftler için DreamTwin',
        'Describe Your Vision': 'Vizyonunu Tanımla',
        'Generate & Customize': 'Oluştur ve Özelleştir',
        'Features': 'Özellikler',
        'Text-to-Image Generation': 'Metin-Görüntü Oluşturma',
        'Look-Alike Portrait Creator': 'Benzeyen Portre Oluşturucu',
        'AI Video Generator': 'AI Video Oluşturucu',
        'SoulChat Companion': 'SoulChat Arkadaşı',
        'Face Swap & Sequence': 'Face Swap ve Sekans',
        'AI Outpainting & Editing': 'AI Outpainting ve Düzenleme',
        'Pricing': 'Fiyatlandırma',
        'Free': 'Ücretsiz',
        'Pro Monthly': 'Pro Aylık',
        'Pro Yearly': 'Pro Yıllık',
        'FAQ': 'SSS',
        'Blog': 'Blog',
        'Contact': 'İletişim',
        'Privacy Policy': 'Gizlilik Politikası',
        'Terms of Service': 'Kullanım Şartları',
        'Affiliate Disclosure': 'Ortaklık Açıklaması',
        'Compare': 'Karşılaştır',
        'vs Candy AI': 'vs Candy AI',
        'vs Seduced AI': 'vs Seduced AI',
        'vs DreamGF': 'vs DreamGF',
        'What is AI SoulGen?': 'AI SoulGen nedir?',
        'Is AI SoulGen free?': 'AI SoulGen ücretsiz mi?',
        'How does the credit system work?': 'Kredi sistemi nasıl çalışır?',
        'Can I generate video?': 'Video oluşturabilir miyim?',
        'Is AI SoulGen legit?': 'AI SoulGen meşru mu?',
        'Does it work on mobile?': 'Mobilde çalışıyor mu?',
        'Ready to Create Your Dream Character?': 'Hayalindeki karakteri yaratmaya hazır mısın?',
        'Join thousands of creators already generating stunning AI characters. Your first image is just seconds away.': 'Zaten çarpıcı AI karakterleri oluşturan binlerce yaratıcıya katıl. İlk görüntün sadece saniyeler uzakta.',
        '© 2026 AI SoulGen. All rights reserved.': '© 2026 AI SoulGen. Tüm hakları saklıdır.',
    },
    'ja': {
        'AI SoulGen': 'AI SoulGen',
        'The ultimate AI soulmate and character generator': '究極のAIソウルメイト＆キャラクタージェネレーター',
        'Create your dream companion in seconds. Realistic portraits, anime characters, and AI video — all from a simple text prompt.': '数秒で理想のパートナーを作成。リアルなポートレート、アニメキャラ、AIビデオ — すべてシンプルなテキストから。',
        'Start Creating Free': '無料で作成開始',
        'Real Character': 'リアルキャラクター',
        'Anime Character': 'アニメキャラクター',
        'DreamTwin Couple': 'DreamTwinカップル',
        'AI SoulGen transforms text prompts into realistic or anime characters': 'AI SoulGenはテキストをリアルまたはアニメキャラクターに変換します',
        'Describe any character and AI SoulGen brings it to life in seconds': 'キャラクターを説明すると、AI SoulGenが数秒で生命を吹き込みます',
        'Create Your Dream': '夢を創造する',
        'Sign Up Free': '無料登録',
        'How It Works': '使い方',
        'Choose Your Style': 'スタイルを選択',
        'Real Character for photorealistic, Anime Character for stylized art, or DreamTwin for romantic pairs': 'フォトリアルにはリアルキャラクター、スタイルアートにはアニメ、ロマンチックなカップルにはDreamTwin',
        'Describe Your Vision': 'ビジョンを説明',
        'Generate & Customize': '生成とカスタマイズ',
        'Features': '機能',
        'Text-to-Image Generation': 'テキストから画像生成',
        'Look-Alike Portrait Creator': 'そっくりポートレート作成',
        'AI Video Generator': 'AIビデオジェネレーター',
        'SoulChat Companion': 'SoulChatコンパニオン',
        'Face Swap & Sequence': 'Face Swapとシーケンス',
        'AI Outpainting & Editing': 'AIアウトペインティングと編集',
        'Pricing': '料金',
        'Free': '無料',
        'Pro Monthly': 'Pro月額',
        'Pro Yearly': 'Pro年額',
        'FAQ': 'よくある質問',
        'Blog': 'ブログ',
        'Contact': 'お問い合わせ',
        'Privacy Policy': 'プライバシーポリシー',
        'Terms of Service': '利用規約',
        'Affiliate Disclosure': 'アフィリエイト開示',
        'Compare': '比較',
        'vs Candy AI': 'vs Candy AI',
        'vs Seduced AI': 'vs Seduced AI',
        'vs DreamGF': 'vs DreamGF',
        'What is AI SoulGen?': 'AI SoulGenとは？',
        'Is AI SoulGen free?': 'AI SoulGenは無料ですか？',
        'How does the credit system work?': 'クレジットシステムの仕組みは？',
        'Can I generate video?': 'ビデオを生成できますか？',
        'Is AI SoulGen legit?': 'AI SoulGenは信頼できますか？',
        'Does it work on mobile?': 'モバイルで動作しますか？',
        'Ready to Create Your Dream Character?': '夢のキャラクターを作成する準備はできましたか？',
        'Join thousands of creators already generating stunning AI characters. Your first image is just seconds away.': 'すでに素晴らしいAIキャラクターを生成している何千ものクリエイターに参加しましょう。最初の画像は数秒先です。',
        '© 2026 AI SoulGen. All rights reserved.': '© 2026 AI SoulGen. All rights reserved.',
    },
    'kr': {
        'AI SoulGen': 'AI SoulGen',
        'The ultimate AI soulmate and character generator': '궁극의 AI 소울메이트 및 캐릭터 생성기',
        'Create your dream companion in seconds. Realistic portraits, anime characters, and AI video — all from a simple text prompt.': '몇 초 만에 꿈의 동반자를 만드세요. 사실적인 초상화, 애니메이션 캐릭터, AI 비디오 — 모두 간단한 텍스트에서.',
        'Start Creating Free': '묣으로 시작하기',
        'Real Character': '리얼 캐릭터',
        'Anime Character': '애니메이션 캐릭터',
        'DreamTwin Couple': 'DreamTwin 커플',
        'AI SoulGen transforms text prompts into realistic or anime characters': 'AI SoulGen은 텍스트를 리얼하거나 애니메이션 캐릭터로 변환합니다',
        'Describe any character and AI SoulGen brings it to life in seconds': '캐릭터를 설명하면 AI SoulGen이 몇 초 만에 생명을 불어넣습니다',
        'Create Your Dream': '꿈을 창조하세요',
        'Sign Up Free': '묣으로 가입',
        'How It Works': '작동 방식',
        'Choose Your Style': '스타일 선택',
        'Real Character for photorealistic, Anime Character for stylized art, or DreamTwin for romantic pairs': '사실감에는 리얼 캐릭터, 스타일 아트에는 애니메이션, 로맨틱 커플에는 DreamTwin',
        'Describe Your Vision': '비전 설명',
        'Generate & Customize': '생성 및 맞춤화',
        'Features': '기능',
        'Text-to-Image Generation': '텍스트-이미지 생성',
        'Look-Alike Portrait Creator': '닮은 초상화 제작자',
        'AI Video Generator': 'AI 비디오 생성기',
        'SoulChat Companion': 'SoulChat 동반자',
        'Face Swap & Sequence': '페이스 스왑 및 시퀀스',
        'AI Outpainting & Editing': 'AI 아웃페인팅 및 편집',
        'Pricing': '가격',
        'Free': '묣',
        'Pro Monthly': 'Pro 월간',
        'Pro Yearly': 'Pro 연간',
        'FAQ': '자주 묻는 질문',
        'Blog': '블로그',
        'Contact': '문의',
        'Privacy Policy': '개인정보 처리방침',
        'Terms of Service': '이용약관',
        'Affiliate Disclosure': '제휴 공개',
        'Compare': '비교',
        'vs Candy AI': 'vs Candy AI',
        'vs Seduced AI': 'vs Seduced AI',
        'vs DreamGF': 'vs DreamGF',
        'What is AI SoulGen?': 'AI SoulGen이란?',
        'Is AI SoulGen free?': 'AI SoulGen은 묣인가요?',
        'How does the credit system work?': '크레딧 시스템은 어떻게 작동하나요?',
        'Can I generate video?': '비디오를 생성할 수 있나요?',
        'Is AI SoulGen legit?': 'AI SoulGen은 신뢰할 수 있나요?',
        'Does it work on mobile?': '모바일에서 작동하나요?',
        'Ready to Create Your Dream Character?': '꿈의 캐릭터를 만들 준비가 되셨나요?',
        'Join thousands of creators already generating stunning AI characters. Your first image is just seconds away.': '이미 멋진 AI 캐릭터를 생성하고 있는 수천 명의 제작자에 참여하세요. 첫 번째 이미지는 몇 초 후에 나옵니다.',
        '© 2026 AI SoulGen. All rights reserved.': '© 2026 AI SoulGen. All rights reserved.',
    },
    'hi': {
        'AI SoulGen': 'AI SoulGen',
        'The ultimate AI soulmate and character generator': 'अंतिम AI सोलमेट और कैरेक्टर जनरेटर',
        'Create your dream companion in seconds. Realistic portraits, anime characters, and AI video — all from a simple text prompt.': 'सेकंड में अपने सपनों का साथी बनाएं। यथार्थवादी चित्र, एनीमे कैरेक्टर और AI वीडियो — सब कुछ एक साधारण टेक्स्ट से।',
        'Start Creating Free': 'मुफ्त में बनाना शुरू करें',
        'Real Character': 'रीयल कैरेक्टर',
        'Anime Character': 'एनीमे कैरेक्टर',
        'DreamTwin Couple': 'DreamTwin जोड़ी',
        'AI SoulGen transforms text prompts into realistic or anime characters': 'AI SoulGen टेक्स्ट को यथार्थवादी या एनीमे कैरेक्टर में बदलता है',
        'Describe any character and AI SoulGen brings it to life in seconds': 'किसी भी कैरेक्टर का वर्णन करें, AI SoulGen उसे सेकंड में जीवंत कर देगा',
        'Create Your Dream': 'अपना सपना बनाएं',
        'Sign Up Free': 'मुफ्त में साइन अप करें',
        'How It Works': 'यह कैसे काम करता है',
        'Choose Your Style': 'अपनी शैली चुनें',
        'Real Character for photorealistic, Anime Character for stylized art, or DreamTwin for romantic pairs': 'फोटोरियलिज्म के लिए रीयल कैरेक्टर, स्टाइलाइज्ड आर्ट के लिए एनीमे, या रोमांटिक जोड़ियों के लिए DreamTwin',
        'Describe Your Vision': 'अपनी दृष्टि का वर्णन करें',
        'Generate & Customize': 'जनरेट और कस्टमाइज़ करें',
        'Features': 'विशेषताएं',
        'Text-to-Image Generation': 'टेक्स्ट-टू-इमेज जनरेशन',
        'Look-Alike Portrait Creator': 'दिखने में मिलते-जुलते पोर्ट्रेट बनाने वाला',
        'AI Video Generator': 'AI वीडियो जनरेटर',
        'SoulChat Companion': 'SoulChat साथी',
        'Face Swap & Sequence': 'फेस स्वैप और सीक्वेंस',
        'AI Outpainting & Editing': 'AI आउटपेंटिंग और एडिटिंग',
        'Pricing': 'मूल्य निर्धारण',
        'Free': 'मुफ्त',
        'Pro Monthly': 'Pro मासिक',
        'Pro Yearly': 'Pro वार्षिक',
        'FAQ': 'अक्सर पूछे जाने वाले प्रश्न',
        'Blog': 'ब्लॉग',
        'Contact': 'संपर्क',
        'Privacy Policy': 'गोपनीयता नीति',
        'Terms of Service': 'सेवा की शर्तें',
        'Affiliate Disclosure': 'एफिलिएट प्रकटीकरण',
        'Compare': 'तुलना करें',
        'vs Candy AI': 'vs Candy AI',
        'vs Seduced AI': 'vs Seduced AI',
        'vs DreamGF': 'vs DreamGF',
        'What is AI SoulGen?': 'AI SoulGen क्या है?',
        'Is AI SoulGen free?': 'क्या AI SoulGen मुफ्त है?',
        'How does the credit system work?': 'क्रेडिट सिस्टम कैसे काम करता है?',
        'Can I generate video?': 'क्या मैं वीडियो जनरेट कर सकता हूं?',
        'Is AI SoulGen legit?': 'क्या AI SoulGen वैध है?',
        'Does it work on mobile?': 'क्या यह मोबाइल पर काम करता है?',
        'Ready to Create Your Dream Character?': 'अपने सपनों के कैरेक्टर को बनाने के लिए तैयार हैं?',
        'Join thousands of creators already generating stunning AI characters. Your first image is just seconds away.': 'हजारों क्रिएटर्स में शामिल हों जो पहले से ही शानदार AI कैरेक्टर बना रहे हैं। आपकी पहली इमेज कुछ सेकंड दूर है।',
        '© 2026 AI SoulGen. All rights reserved.': '© 2026 AI SoulGen. सर्वाधिकार सुरक्षित।',
    },
}

def extract_texts(html):
    """Extract all text nodes from HTML (content between tags)."""
    texts = set()
    # Match text between > and <
    for match in re.findall(r'>([^<]{3,})<', html):
        text = match.strip()
        if text and re.search(r'[a-zA-Z]{3,}', text):
            texts.add(text)
    return texts

def apply_translations(html, translations):
    """Apply translations to HTML, longest first to avoid partial replacements."""
    # Sort by length descending
    items = sorted(translations.items(), key=lambda x: len(x[0]), reverse=True)
    for en, tr in items:
        if en in html:
            html = html.replace(en, tr)
    return html

def main():
    with open('index.html', 'r', encoding='utf-8') as f:
        en_html = f.read()
    
    # Extract all English texts
    en_texts = extract_texts(en_html)
    print(f"Found {len(en_texts)} English text nodes in index.html")
    
    # Save untranslated texts for reference
    untranslated = {}
    
    for lang, info in LANGS.items():
        print(f"\n=== Processing {lang} ({info['name']}) ===")
        
        lang_path = f"{lang}/index.html"
        if not os.path.exists(lang_path):
            print(f"  WARNING: {lang_path} not found, copying from EN")
            os.makedirs(lang, exist_ok=True)
            lang_html = en_html
        else:
            with open(lang_path, 'r', encoding='utf-8') as f:
                lang_html = f.read()
        
        # Get translations for this lang
        trans = TRANSLATIONS.get(lang, {})
        
        # Count how many EN texts remain
        lang_texts = extract_texts(lang_html)
        en_remaining = [t for t in lang_texts if t in en_texts and t not in trans and len(t) > 10]
        print(f"  English texts remaining before: {len(en_remaining)}")
        
        # Apply translations
        lang_html = apply_translations(lang_html, trans)
        
        # Update meta tags
        lang_html = lang_html.replace('lang="en"', f'lang="{lang}"')
        lang_html = lang_html.replace('og:locale" content="en_US"', f'og:locale" content="{info["locale"]}"')
        
        # Update canonical
        lang_html = lang_html.replace('href="https://ai-soulgen.com/"', f'href="https://ai-soulgen.com/{lang}/"')
        
        # Fix paths for subfolder
        lang_html = lang_html.replace('href="index.html"', 'href="../index.html"')
        lang_html = lang_html.replace('href="privacy.html"', 'href="../privacy.html"')
        lang_html = lang_html.replace('href="terms.html"', 'href="../terms.html"')
        lang_html = lang_html.replace('href="affiliate-disclosure.html"', 'href="../affiliate-disclosure.html"')
        lang_html = lang_html.replace('src="images/', 'src="../images/')
        lang_html = lang_html.replace('href="images/', 'href="../images/')
        
        # Write back
        with open(lang_path, 'w', encoding='utf-8') as f:
            f.write(lang_html)
        
        # Check remaining
        lang_texts_after = extract_texts(lang_html)
        en_remaining_after = [t for t in lang_texts_after if t in en_texts and t not in trans and len(t) > 10]
        print(f"  English texts remaining after: {len(en_remaining_after)}")
        if en_remaining_after:
            untranslated[lang] = en_remaining_after[:20]
    
    # Save untranslated for future reference
    with open('untranslated_texts.json', 'w', encoding='utf-8') as f:
        json.dump(untranslated, f, ensure_ascii=False, indent=2)
    
    print(f"\n=== Done ===")
    print(f"Untranslated texts saved to untranslated_texts.json")

if __name__ == '__main__':
    main()
