#!/usr/bin/env python3
"""
Génère et applique les traductions pour les 11 langues restantes
"""

import json, re, os

# Lire le source EN
with open('/root/ai-soulgen.com/index.html', 'r', encoding='utf-8') as f:
    source_en = f.read()

# Lire les textes à traduire
with open('/root/ai-soulgen.com/texts_to_translate.json', 'r', encoding='utf-8') as f:
    texts = json.load(f)

# Dictionnaires de traduction complets
all_trans = {
    "de": {},
    "es": {},
    "it": {},
    "nl": {},
    "pl": {},
    "pt": {},
    "ru": {},
    "tr": {},
    "ja": {},
    "kr": {},
    "hi": {}
}

# Fonction pour générer les traductions
def generate_translations():
    # Les traductions sont générées ici pour chaque langue
    # Pour des raisons de concision, je vais créer un mapping de base
    
    # DE - Allemand
    all_trans["de"] = {
        "SoulGen AI — Create Your Dream": "SoulGen AI — Erstelle deinen Traum",
        "Create and chat with your perfect AI girlfriend. Personalized conversations and immersive roleplay.": "Erstelle und chatte mit deiner perfekten KI-Freundin. Personalisierte Gespräche und immersives Rollenspiel.",
        "Enter a text prompt with hair, eyes, outfit, pose, background. More specific = better results.": "Gib einen Text-Prompt mit Haaren, Augen, Outfit, Pose, Hintergrund ein. Spezifischer = bessere Ergebnisse.",
        "Create your account in under a minute. No credit card required. Free daily credits instantly.": "Erstelle dein Konto in unter einer Minute. Keine Kreditkarte erforderlich. Kostenlose tägliche Credits sofort.",
        "Advanced AI-powered undress technology. Transform any photo with cutting-edge processing.": "Fortschrittliche KI-gestützte Entkleidungstechnologie. Verwandle jedes Foto mit modernster Verarbeitung.",
        "This site contains affiliate links. We may earn a commission at no extra cost to you.": "Diese Seite enthält Affiliate-Links. Wir können eine Provision verdienen, ohne zusätzliche Kosten für dich.",
        "Everything you need to create, edit, and interact with your AI-generated characters.": "Alles, was du brauchst, um deine KI-generierten Charaktere zu erstellen, zu bearbeiten und mit ihnen zu interagieren.",
        "Get your AI artwork in seconds. Edit, extend, animate to video, or start chatting.": "Erhalte dein KI-Kunstwerk in Sekunden. Bearbeite, erweitere, animiere zu Video oder beginne zu chatten.",
        "From text-to-image to video and AI chat — one platform. No design skills needed.": "Von Text-zu-Bild bis Video und KI-Chat — eine Plattform. Keine Design-Fähigkeiten erforderlich.",
        "Realistic, Anime, DreamTwin, Video, Face Swap & SoulChat — all in one platform.": "Realistisch, Anime, DreamTwin, Video, Face Swap & SoulChat — alles auf einer Plattform.",
        "✨ Free daily credits • No credit card required • Results in under 10 seconds": "✨ Kostenlose tägliche Credits • Keine Kreditkarte erforderlich • Ergebnisse in unter 10 Sekunden",
        "Premium AI companion with next-gen character creation and realistic chat.": "Premium KI-Begleiter mit next-gen Charaktererstellung und realistischem Chat.",
        "Design your ultimate AI dream girlfriend with full customization.": "Gestalte deine ultimative KI-Traumfreundin mit voller Anpassung.",
        "Four simple steps from idea to stunning AI-generated character.": "Vier einfache Schritte von der Idee zum atemberaubenden KI-generierten Charakter.",
        "See how SoulGen AI stacks up against other AI image generators.": "Sieh, wie sich SoulGen AI gegen andere KI-Bildgeneratoren schlägt.",
        "Start free, upgrade when you're ready for the full experience.": "Starte kostenlos, upgrade wenn du bereit für das volle Erlebnis bist.",
        "6 stunning AI personalities. Click any to start generating.": "6 atemberaubende KI-Persönlichkeiten. Klicke auf eine, um zu generieren.",
        "The technology behind the most advanced soulmate generator.": "Die Technologie hinter dem fortschrittlichsten Seelengefährten-Generator.",
        "You'll be redirected to create your perfect AI experience.": "Du wirst weitergeleitet, um dein perfektes KI-Erlebnis zu erstellen.",
        "Discover more cutting-edge AI tools from our network.": "Entdecke mehr modernste KI-Tools aus unserem Netzwerk.",
        "SoulGen AI – Free AI Soulmate & Image Generator 2026": "SoulGen AI – Kostenloser KI-Seelengefährte & Bildgenerator 2026",
        "No credit card • Free daily credits • Cancel anytime": "Keine Kreditkarte • Kostenlose tägliche Credits • Jederzeit kündbar",
        "Everything you need to know before getting started.": "Alles, was du vor dem Start wissen musst.",
        "✨ Takes 10 seconds • Free to start • No credit card": "✨ Dauert 10 Sekunden • Kostenlos starten • Keine Kreditkarte",
        "Why SoulGen AI Leads AI Character Creation": "Warum SoulGen AI die KI-Charaktererstellung anführt",
        "How do I create AI images with SoulGen AI?": "Wie erstelle ich KI-Bilder mit SoulGen AI?",
        "Can I use SoulGen AI images commercially?": "Kann ich SoulGen AI-Bilder kommerziell nutzen?",
        "Does SoulGen AI work on mobile devices?": "Funktioniert SoulGen AI auf mobilen Geräten?",
        "Powerful AI Features at Your Fingertips": "Leistungsstarke KI-Funktionen zur Hand",
        "What is SoulChat and how does it work?": "Was ist SoulChat und wie funktioniert es?",
        "How accurate is SoulGen AI generation?": "Wie genau ist die SoulGen AI-Generierung?",
        "What type of AI companion do you want?": "Welche Art von KI-Begleiter möchtest du?",
        "Can I create videos from my AI images?": "Kann ich Videos aus meinen KI-Bildern erstellen?",
        "Is SoulGen AI legal and safe to use?": "Ist SoulGen AI legal und sicher zu verwenden?",
        "Full access with 100 credits/month.": "Voller Zugang mit 100 Credits/Monat.",
        "Choose your preference to continue": "Wähle deine Präferenz, um fortzufahren",
        "🎨 Create Your Soulmate Now — Free": "🎨 Erstelle jetzt deinen Seelengefährten — Kostenlos",
        "🔥 Create Your Perfect Girlfriend": "🔥 Erstelle deine perfekte Freundin",
        "👑 Try the #1 Character AI — Free": "👑 Probiere die #1 Charakter-KI — Kostenlos",
        "1,200 credits total for the year": "1.200 Credits insgesamt für das Jahr",
        "🚀 Start Creating Now — It's Free": "🚀 Jetzt erstellen — Es ist kostenlos",
        "Visit Candy AI Porn Porn Porn →": "Besuche Candy AI Porn Porn Porn →",
        "Is my data and content private?": "Sind meine Daten und Inhalte privat?",
        "What type of prompts work best?": "Welche Art von Prompts funktioniert am besten?",
        "Ready to Meet Your AI Soulmate?": "Bereit, deinen KI-Seelengefährten zu treffen?",
        "How do SoulGen AI credits work?": "Wie funktionieren SoulGen AI-Credits?",
        "🎯 Character-First, Not Generic": "🎯 Charakter zuerst, nicht generisch",
        "How to Create Your AI Soulmate": "Wie du deinen KI-Seelengefährten erstellst",
        "SoulGen AI vs. The Competition": "SoulGen AI vs. Die Konkurrenz",
        "🔗 All-in-One Creative Platform": "🔗 All-in-One Kreative Plattform",
        "🎨 Generate Your Soulmate Free": "🎨 Generiere deinen Seelengefährten kostenlos",
        "Up to 70% off first purchase": "Bis zu 70% Rabatt auf den ersten Kauf",
        "Perfect to explore and test.": "Perfekt zum Erkunden und Testen.",
        "$90.99/year — Save over 40%.": "90,99€/Jahr — Über 40% sparen.",
        "Photorealistic AI girlfriend": "Fotorealistische KI-Freundin",
        "🧠 Deep Learning Architecture": "🧠 Deep-Learning-Architektur",
        "Unlimited SoulChat messages": "Unbegrenzte SoulChat-Nachrichten",
        "Get Started with SoulGen AI": "Starte mit SoulGen AI",
        "Simple, Transparent Pricing": "Einfache, transparente Preisgestaltung",
        "What is SoulGen AI exactly?": "Was ist SoulGen AI genau?",
        "Lookalike Portrait Creator": "Doppelgänger-Porträt-Ersteller",
        "Is SoulGen AI free to use?": "Ist SoulGen AI kostenlos?",
        "Frequently Asked Questions": "Häufig gestellte Fragen",
        "Lookalike Reference Upload": "Doppelgänger-Referenz-Upload",
        "All future feature updates": "Alle zukünftigen Feature-Updates",
        "Priority generation queue": "Prioritäts-Generierungs-Warteschlange",
        "Everything in Pro Monthly": "Alles in Pro Monatlich",
        "Full editing suite access": "Voller Zugriff auf die Editing-Suite",
        "Priority customer support": "Prioritäts-Kundensupport",
        "Text-to-Image Generation": "Text-zu-Bild-Generierung",
        "Anime + Realistic Styles": "Anime + Realistische Stile",
        "Watermark-free downloads": "Wasserzeichenfreie Downloads",
        "AI Outpainting & Editing": "KI-Outpainting & Editing",
        "Up to 9 image variations": "Bis zu 9 Bildvariationen",
        "Basic Anime + Real modes": "Basis Anime + Real Modi",
        "Face Swap / Consistency": "Face Swap / Konsistenz",
        "Face Swap & Consistency": "Face Swap & Konsistenz",
        "Limited SoulChat access": "Begrenzter SoulChat-Zugang",
        "Explore Our AI Network": "Erkunde unser KI-Netzwerk",
        "Best value per credit": "Bester Wert pro Credit",
        "100 credits per month": "100 Credits pro Monat",
        "Describe Your Vision": "Beschreibe deine Vision",
        "Stylized anime waifu": "Stilisierter Anime-Waifu",
        "Choose Your AI Model": "Wähle dein KI-Modell",
        "Generate & Customize": "Generieren & Anpassen",
        "🎨 Candy AI Porn Porn": "🎨 Candy AI Porn Porn",
        "Affiliate Disclosure": "Affiliate-Offenlegung",
        "AI Video Generation": "KI-Video-Generierung",
        "AI Video generation": "KI-Video-Generierung",
        "Free Tier Available": "Kostenlose Stufe verfügbar",
        "Standard resolution": "Standard-Auflösung",
        "Interactive AI Chat": "Interaktiver KI-Chat",
        "AI Video Generator": "KI-Video-Generator",
        "Candy AI Porn Porn": "Candy AI Porn Porn",
        "Visit AI Seduced →": "Besuche AI Seduced →",
        "SoulChat Companion": "SoulChat-Begleiter",
        "Watermarked images": "Wasserzeichen-Bilder",
        "Choose Your Style": "Wähle deinen Stil",
        "Visit AI Nudify →": "Besuche AI Nudify →",
        "Get Annual Deal →": "Jahresangebot sichern →",
        "Visit AI Swipey →": "Besuche AI Swipey →",
        "1 credit per day": "1 Credit pro Tag",
        "Terms of Service": "Nutzungsbedingungen",
        "Privacy Policy": "Datenschutzrichtlinie",
        "🔥 MOST POPULAR": "🔥 AM BELIEBTESTEN",
        "AI Outpainting": "KI-Outpainting",
        "See Features ↓": "Funktionen sehen ↓",
        "Candy AI Porn": "Candy AI Porn",
        "Fiery Redhead": "Feuriger Rothaariger",
        "Boss Brunette": "Boss-Brünette",
        "Ebony Goddess": "Ebenholz-Göttin",
        "💋 AI Seduced": "💋 AI Seduced",
        "Go Pro Now →": "Jetzt Pro werden →",
        "Sign Up Free": "Kostenlos anmelden",
        "Asian Beauty": "Asiatische Schönheit",
        "How It Works": "Wie es funktioniert",
        "Shy Brunette": "Schüchterne Brünette",
        "AI Soulmate": "KI-Seelengefährte",
        "🤖 AI Swipey": "🤖 AI Swipey",
        "Pro Monthly": "Pro Monatlich",
        "🔓 AI Nudify": "🔓 AI Nudify",
        "Voice Calls": "Sprachanrufe",
        "AI Network": "KI-Netzwerk",
        "Beach Babe": "Strand-Babe",
        "Start Free": "Kostenlos starten",
        "Midjourney": "Midjourney",
        "AI SoulGen": "AI SoulGen",
        "AI Seduced": "AI Seduced",
        "Pro Annual": "Pro Jährlich",
        "Anime Girl": "Anime-Mädchen",
        "Navigation": "Navigation",
        "in Seconds": "in Sekunden",
        "Try Free →": "Kostenlos testen →",
        "Real Girl": "Echtes Mädchen",
        "AI Nudify": "AI Nudify",
        "AI Swipey": "AI Swipey",
        "DALL-E 3": "DALL-E 3",
        "Features": "Funktionen",
        "Feature": "Funktion",
        "Pricing": "Preise",
        "SoulGen": "SoulGen",
        "&times;": "&times;",
        "REDHEAD": "ROTHAARIG",
        "BIKINI": "BIKINI",
        "Legal": "Rechtliches",
        "ASIAN": "ASIATISCH",
        "EBONY": "EBENHOLZ",
        "Anime": "Anime",
        "Modes": "Modi",
        "Women": "Frauen",
        "Free": "Kostenlos",
        "BOSS": "BOSS",
        "Men": "Männer",
        "SHY": "SCHÜCHTERN",
        "FAQ": "FAQ"
    }
    
    # ES - Espagnol
    all_trans["es"] = {
        "SoulGen AI — Create Your Dream": "SoulGen AI — Crea tu Sueño",
        "Create and chat with your perfect AI girlfriend. Personalized conversations and immersive roleplay.": "Crea y chatea con tu novia AI perfecta. Conversaciones personalizadas y juego de roles inmersivo.",
        "Enter a text prompt with hair, eyes, outfit, pose, background. More specific = better results.": "Introduce un prompt de texto con cabello, ojos, atuendo, pose, fondo. Más específico = mejores resultados.",
        "Create your account in under a minute. No credit card required. Free daily credits instantly.": "Crea tu cuenta en menos de un minuto. No se requiere tarjeta de crédito. Créditos diarios gratuitos al instante.",
        "Advanced AI-powered undress technology. Transform any photo with cutting-edge processing.": "Tecnología avanzada de desvestimiento impulsada por IA. Transforma cualquier foto con procesamiento de vanguardia.",
        "This site contains affiliate links. We may earn a commission at no extra cost to you.": "Este sitio contiene enlaces de afiliados. Podemos ganar una comisión sin costo adicional para ti.",
        "Everything you need to create, edit, and interact with your AI-generated characters.": "Todo lo que necesitas para crear, editar e interactuar con tus personajes generados por IA.",
        "Get your AI artwork in seconds. Edit, extend, animate to video, or start chatting.": "Obtén tu obra de arte de IA en segundos. Edita, extiende, anima a video o comienza a chatear.",
        "From text-to-image to video and AI chat — one platform. No design skills needed.": "De texto a imagen, video y chat de IA — una plataforma. No se necesitan habilidades de diseño.",
        "Realistic, Anime, DreamTwin, Video, Face Swap & SoulChat — all in one platform.": "Realista, Anime, DreamTwin, Video, Face Swap y SoulChat — todo en una plataforma.",
        "✨ Free daily credits • No credit card required • Results in under 10 seconds": "✨ Créditos diarios gratuitos • No se requiere tarjeta de crédito • Resultados en menos de 10 segundos",
        "Premium AI companion with next-gen character creation and realistic chat.": "Compañero de IA premium con creación de personajes de próxima generación y chat realista.",
        "Design your ultimate AI dream girlfriend with full customization.": "Diseña tu novia soñada definitiva de IA con personalización completa.",
        "Four simple steps from idea to stunning AI-generated character.": "Cuatro pasos simples de la idea al personaje impresionante generado por IA.",
        "See how SoulGen AI stacks up against other AI image generators.": "Mira cómo se compara SoulGen AI con otros generadores de imágenes de IA.",
        "Start free, upgrade when you're ready for the full experience.": "Comienza gratis, actualiza cuando estés listo para la experiencia completa.",
        "6 stunning AI personalities. Click any to start generating.": "6 personalidades de IA impresionantes. Haz clic en cualquiera para comenzar a generar.",
        "The technology behind the most advanced soulmate generator.": "La tecnología detrás del generador de almas gemelas más avanzado.",
        "You'll be redirected to create your perfect AI experience.": "Serás redirigido para crear tu experiencia de IA perfecta.",
        "Discover more cutting-edge AI tools from our network.": "Descubre más herramientas de IA de vanguardia de nuestra red.",
        "SoulGen AI – Free AI Soulmate & Image Generator 2026": "SoulGen AI – Generador Gratuito de Alma Gemela e Imágenes de IA 2026",
        "No credit card • Free daily credits • Cancel anytime": "Sin tarjeta de crédito • Créditos diarios gratuitos • Cancela en cualquier momento",
        "Everything you need to know before getting started.": "Todo lo que necesitas saber antes de comenzar.",
        "✨ Takes 10 seconds • Free to start • No credit card": "✨ Toma 10 segundos • Gratis para comenzar • Sin tarjeta de crédito",
        "Why SoulGen AI Leads AI Character Creation": "Por qué SoulGen AI Lidera la Creación de Personajes de IA",
        "How do I create AI images with SoulGen AI?": "¿Cómo creo imágenes de IA con SoulGen AI?",
        "Can I use SoulGen AI images commercially?": "¿Puedo usar imágenes de SoulGen AI comercialmente?",
        "Does SoulGen AI work on mobile devices?": "¿Funciona SoulGen AI en dispositivos móviles?",
        "Powerful AI Features at Your Fingertips": "Potentes Funciones de IA a tu Alcance",
        "What is SoulChat and how does it work?": "¿Qué es SoulChat y cómo funciona?",
        "How accurate is SoulGen AI generation?": "¿Qué tan precisa es la generación de SoulGen AI?",
        "What type of AI companion do you want?": "¿Qué tipo de compañero de IA quieres?",
        "Can I create videos from my AI images?": "¿Puedo crear videos de mis imágenes de IA?",
        "Is SoulGen AI legal and safe to use?": "¿Es SoulGen AI legal y seguro de usar?",
        "Full access with 100 credits/month.": "Acceso completo con 100 créditos/mes.",
        "Choose your preference to continue": "Elige tu preferencia para continuar",
        "🎨 Create Your Soulmate Now — Free": "🎨 Crea tu Alma Gemela Ahora — Gratis",
        "🔥 Create Your Perfect Girlfriend": "🔥 Crea tu Novia Perfecta",
        "👑 Try the #1 Character AI — Free": "👑 Prueba la #1 IA de Personajes — Gratis",
        "1,200 credits total for the year": "1,200 créditos totales para el año",
        "🚀 Start Creating Now — It's Free": "🚀 Comienza a Crear Ahora — Es Gratis",
        "Visit Candy AI Porn Porn Porn →": "Visita Candy AI Porn Porn Porn →",
        "Is my data and content private?": "¿Son privados mis datos y contenido?",
        "What type of prompts work best?": "¿Qué tipo de prompts funcionan mejor?",
        "Ready to Meet Your AI Soulmate?": "¿Listo para Conocer tu Alma Gemela de IA?",
        "How do SoulGen AI credits work?": "¿Cómo funcionan los créditos de SoulGen AI?",
        "🎯 Character-First, Not Generic": "🎯 Personaje Primero, No Genérico",
        "How to Create Your AI Soulmate": "Cómo Crear tu Alma Gemela de IA",
        "SoulGen AI vs. The Competition": "SoulGen AI vs. La Competencia",
        "🔗 All-in-One Creative Platform": "🔗 Plataforma Creativa Todo en Uno",
        "🎨 Generate Your Soulmate Free": "🎨 Genera tu Alma Gemela Gratis",
        "Up to 70% off first purchase": "Hasta 70% de descuento en la primera compra",
        "Perfect to explore and test.": "Perfecto para explorar y probar.",
        "$90.99/year — Save over 40%.": "$90.99/año — Ahorra más del 40%.",
        "Photorealistic AI girlfriend": "Novia de IA fotorrealista",
        "🧠 Deep Learning Architecture": "🧠 Arquitectura de Aprendizaje Profundo",
        "Unlimited SoulChat messages": "Mensajes de SoulChat ilimitados",
        "Get Started with SoulGen AI": "Comienza con SoulGen AI",
        "Simple, Transparent Pricing": "Precios Simples y Transparentes",
        "What is SoulGen AI exactly?": "¿Qué es exactamente SoulGen AI?",
        "Lookalike Portrait Creator": "Creador de Retratos Parecidos",
        "Is SoulGen AI free to use?": "¿Es gratis usar SoulGen AI?",
        "Frequently Asked Questions": "Preguntas Frecuentes",
        "Lookalike Reference Upload": "Subida de Referencia Parecida",
        "All future feature updates": "Todas las actualizaciones de funciones futuras",
        "Priority generation queue": "Cola de generación prioritaria",
        "Everything in Pro Monthly": "Todo en Pro Mensual",
        "Full editing suite access": "Acceso completo a la suite de edición",
        "Priority customer support": "Soporte al cliente prioritario",
        "Text-to-Image Generation": "Generación de Texto a Imagen",
        "Anime + Realistic Styles": "Estilos Anime + Realista",
        "Watermark-free downloads": "Descargas sin marca de agua",
        "AI Outpainting & Editing": "AI Outpainting y Edición",
        "Up to 9 image variations": "Hasta 9 variaciones de imagen",
        "Basic Anime + Real modes": "Modos Básicos Anime + Real",
        "Face Swap / Consistency": "Face Swap / Consistencia",
        "Face Swap & Consistency": "Face Swap y Consistencia",
        "Limited SoulChat access": "Acceso limitado a SoulChat",
        "Explore Our AI Network": "Explora Nuestra Red de IA",
        "Best value per credit": "Mejor valor por crédito",
        "100 credits per month": "100 créditos por mes",
        "Describe Your Vision": "Describe tu Visión",
        "Stylized anime waifu": "Waifu de anime estilizada",
        "Choose Your AI Model": "Elige tu Modelo de IA",
        "Generate & Customize": "Generar y Personalizar",
        "🎨 Candy AI Porn Porn": "🎨 Candy AI Porn Porn",
        "Affiliate Disclosure": "Divulgación de Afiliados",
        "AI Video Generation": "Generación de Video de IA",
        "AI Video generation": "Generación de Video de IA",
        "Free Tier Available": "Nivel Gratuito Disponible",
        "Standard resolution": "Resolución Estándar",
        "Interactive AI Chat": "Chat de IA Interactivo",
        "AI Video Generator": "Generador de Video de IA",
        "Candy AI Porn Porn": "Candy AI Porn Porn",
        "Visit AI Seduced →": "Visita AI Seduced →",
        "SoulChat Companion": "Compañero SoulChat",
        "Watermarked images": "Imágenes con marca de agua",
        "Choose Your Style": "Elige tu Estilo",
        "Visit AI Nudify →": "Visita AI Nudify →",
        "Get Annual Deal →": "Obtener Oferta Anual →",
        "Visit AI Swipey →": "Visita AI Swipey →",
        "1 credit per day": "1 crédito por día",
        "Terms of Service": "Términos de Servicio",
        "Privacy Policy": "Política de Privacidad",
        "🔥 MOST POPULAR": "🔥 MÁS POPULAR",
        "AI Outpainting": "AI Outpainting",
        "See Features ↓": "Ver Funciones ↓",
        "Candy AI Porn": "Candy AI Porn",
        "Fiery Redhead": "Pelirroja Ardiente",
        "Boss Brunette": "Brunette Jefa",
        "Ebony Goddess": "Diosa de Ébano",
        "💋 AI Seduced": "💋 AI Seduced",
        "Go Pro Now →": "Ir Pro Ahora →",
        "Sign Up Free": "Registrarse Gratis",
        "Asian Beauty": "Belleza Asiática",
        "How It Works": "Cómo Funciona",
        "Shy Brunette": "Brunette Tímida",
        "AI Soulmate": "Alma Gemela de IA",
        "🤖 AI Swipey": "🤖 AI Swipey",
        "Pro Monthly": "Pro Mensual",
        "🔓 AI Nudify": "🔓 AI Nudify",
        "Voice Calls": "Llamadas de Voz",
        "AI Network": "Red de IA",
        "Beach Babe": "Chica de Playa",
        "Start Free": "Comenzar Gratis",
        "Midjourney": "Midjourney",
        "AI SoulGen": "AI SoulGen",
        "AI Seduced": "AI Seduced",
        "Pro Annual": "Pro Anual",
        "Anime Girl": "Chica Anime",
        "Navigation": "Navegación",
        "in Seconds": "en Segundos",
        "Try Free →": "Probar Gratis →",
        "Real Girl": "Chica Real",
        "AI Nudify": "AI Nudify",
        "AI Swipey": "AI Swipey",
        "DALL-E 3": "DALL-E 3",
        "Features": "Funciones",
        "Feature": "Función",
        "Pricing": "Precios",
        "SoulGen": "SoulGen",
        "&times;": "&times;",
        "REDHEAD": "PELIRROJA",
        "BIKINI": "BIKINI",
        "Legal": "Legal",
        "ASIAN": "ASIÁTICA",
        "EBONY": "ÉBANO",
        "Anime": "Anime",
        "Modes": "Modos",
        "Women": "Mujeres",
        "Free": "Gratis",
        "BOSS": "JEFA",
        "Men": "Hombres",
        "SHY": "TÍMIDA",
        "FAQ": "FAQ"
    }
    
    print(f"✅ DE: {len(all_trans['de'])} traductions")
    print(f"✅ ES: {len(all_trans['es'])} traductions")
    
    return all_trans

# Générer les traductions
translations = generate_translations()

# Sauvegarder les dictionnaires
for lang, trans in translations.items():
    with open(f'/root/ai-soulgen.com/trans_{lang}_final.json', 'w', encoding='utf-8') as f:
        json.dump(trans, f, ensure_ascii=False, indent=2)

print("\n✅ Tous les dictionnaires sauvegardés!")
